#!/bin/ash

SEARCH='hackpgh%20OR%20hackpittsburgh%20OR%20%22hack%20pittsburgh%22'
LED_SIGN=/dev/tts/1

#LED_SIGN=tmp
cd /jffs

LAST_ID=`cat twitter_last_written_id`
if [ -z $LAST_ID ]; then
  LAST_ID=0
fi

QUERY="http://search.twitter.com/search.json?result_type=recent&show_user=false&rpp=1&count=1&since_id=$LAST_ID&q=$SEARCH"
echo -n "$QUERY" > twitter_query
wget -q -O - $QUERY > twitter_raw_res
rv=$?
if [ $rv -ne 0 ]; then
  echo "error: wget returned $rv"
  exit 1
fi

TWITTER_USER=`cat twitter_raw_res \
    | sed -n -e 's/.*"from_user":"\([^"]*\)".*/\1/p'`
echo -n "$TWITTER_USER" > twitter_user

TWITTER_MSG=`cat twitter_raw_res \
    | sed -n -e 's/.*"text":"\([^"]*\)".*/\1/p'`
echo -n "$TWITTER_MSG" > twitter_msg

TWITTER_ID=`cat twitter_raw_res \
    | sed -n -e 's/.*"id":\([^,]*\).*/\1/p'`
echo -n "$TWITTER_ID" > twitter_id

if [ -n "$TWITTER_USER" ] \
   && [ -n "$TWITTER_MSG" ] \
   && [ -n "$TWITTER_ID" ] \
   && [ "$TWITTER_ID" -gt "$LAST_ID" ]; then
  echo "new"
  echo -n $TWITTER_ID > twitter_last_written_id
  echo -e -n "\x1f" >> $LED_SIGN # beep!
  echo -e -n "\x1c2$TWITTER_USER:\x1c1$TWITTER_MSG\n" >> $LED_SIGN
fi
